#!/usr/bin/env python3
"""Bundle the planner into one file that works from file:// (no web server).

The served app at web/index.html is the real one: it loads data/*.json at
runtime, so correcting a price means editing JSON. This build exists only so the
player can double-click a single file. Re-run it after changing data or source.

    python3 tools/build_offline.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "planner-offline.html"


def strip_module_syntax(text: str, drop_imports: bool = False) -> str:
    if drop_imports:
        text = re.sub(r"^import\s+\{[^}]*\}\s+from\s+'[^']*';\s*$", "", text, flags=re.M)
        text = re.sub(r"^import\s+[^\n]*from\s+'[^']*';\s*$", "", text, flags=re.M)
    return re.sub(r"^export\s+", "", text, flags=re.M)


def main() -> None:
    html = (ROOT / "web" / "index.html").read_text()
    missions = json.loads((ROOT / "data" / "missions.json").read_text())
    prices = json.loads((ROOT / "data" / "prices.json").read_text())

    planner = strip_module_syntax((ROOT / "src" / "planner.js").read_text())
    i18n = strip_module_syntax((ROOT / "src" / "i18n.js").read_text())
    app = strip_module_syntax((ROOT / "src" / "app.js").read_text(), drop_imports=True)

    data = json.dumps({"missions": missions, "prices": prices}, separators=(",", ":"))
    # </script> inside JSON would close the tag early.
    data = data.replace("</", "<\\/")

    bundle = (
        f'<script>window.__PATHFINDER_DATA__={data};</script>\n'
        f'<script>\n{planner}\n{i18n}\n{app}\n</script>'
    )
    tag = '<script type="module" src="../src/app.js"></script>'
    if tag not in html:
        raise SystemExit("web/index.html no longer loads ../src/app.js — update this script")
    html = html.replace(tag, bundle)
    html = html.replace(
        "<title>Pathfinder", "<!-- generated by tools/build_offline.py, do not edit -->\n<title>Pathfinder"
    )
    OUT.write_text(html)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
