/**
 * Bundle YMCA into one installable userscript.
 *
 * The point of the build is that the algorithm is NOT duplicated: src/planner.js,
 * src/import-game.js and the prerequisite mapping from tools/build_from_game.mjs
 * are the same sources the tests run against, inlined here. Change them once and
 * both the static app and the userscript follow.
 *
 *   node tools/build_ymca.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const ROOT = new URL('..', import.meta.url);
const read = (p) => readFileSync(new URL(p, ROOT), 'utf8');

/** Version lives here, and nowhere else. Steps of 0.0.1, starting at 0.0.0. */
export const VERSION = '0.0.71';

const stripExports = (src) => src.replace(/^export\s+/gm, '');
const cutAtMarker = (src, marker) => {
    const i = src.indexOf(marker);
    return i === -1 ? src : src.slice(0, i);
};
const stripImports = (src) =>
    src.replace(/^import\s+[^;]*;\s*$/gm, '');

const HEADER = `// ==UserScript==
// @name         YMCA — Your Mission Chief Alpha
// @namespace    https://github.com/Kev7ke/pathfinder
// @version      ${VERSION}
// @description  A tool set for MissionChief: build planning, bulk renaming, and a way to hand game data back for support.
// @author       Kev7ke (built with Claude Code)
// @homepageURL  https://github.com/Kev7ke/pathfinder
// @downloadURL  https://raw.githubusercontent.com/Kev7ke/pathfinder/claude/keen-hawking-g3z0ph/userscripts/ymca.user.js
// @updateURL    https://raw.githubusercontent.com/Kev7ke/pathfinder/claude/keen-hawking-g3z0ph/userscripts/ymca.user.js
// @match        *://*.missionchief.com/*
// @match        *://missionchief.com/*
// @match        *://*.missionchief.co.uk/*
// @match        *://missionchief.co.uk/*
// @match        *://*.missionchief-australia.com/*
// @match        *://*.missionchief-japan.com/*
// @match        *://*.missionchief-korea.com/*
// @run-at       document-idle
// @grant        GM_registerMenuCommand
// @grant        GM_xmlhttpRequest
// @grant        GM_info
// @connect      api.lss-manager.de
// ==/UserScript==

/*
 * Generated by tools/build_ymca.mjs — do not edit this file.
 * Sources: userscripts/src/*.js, src/planner.js, src/import-game.js,
 * tools/build_from_game.mjs, data/prices.json, data/vehicle-types.json, data/vehicle-flags.json
 */
`;

const BOOT = `
// ---------- boot ----------
YMCA.logger = logger;

/**
 * Where YMCA lives in the page.
 *
 * The navbar entry is the one to have: it sits with the game's own menus, the
 * way LSS-Manager does. The floating button is the fallback, and it only shows
 * when the navbar could not be found — so "no way in" still means "not
 * running" rather than "the markup moved".
 */
const NAV_SELECTORS = [
    '#navbar-main-collapse > ul',
    '#navbar-main-collapse ul.navbar-nav',
    '.navbar-fixed-top .navbar-nav',
    '.navbar-nav',
];

function mountNav() {
    if (document.getElementById('ymca-nav')) return true;
    let list = null;
    let used = null;
    for (const sel of NAV_SELECTORS) {
        list = document.querySelector(sel);
        if (list) { used = sel; break; }
    }
    if (!list) return false;
    const li = document.createElement('li');
    li.id = 'ymca-nav';
    const a = document.createElement('a');
    a.href = '#';
    a.textContent = 'YMCA';
    a.style.fontWeight = '700';
    a.style.letterSpacing = '.06em';
    li.append(a);
    // On the li, not the anchor: the game's navbar items are padded by their
    // list item, so a click can land either side of the text.
    li.addEventListener('click', (e) => {
        e.preventDefault();
        openWindow();
    });
    list.append(li);
    logger.info('shell', 'navbar entry placed', used);
    return true;
}

function mountFab() {
    if (document.getElementById('ymca-fab') || !document.body) return;
    const btn = document.createElement('button');
    btn.id = 'ymca-fab';
    btn.type = 'button';
    btn.textContent = 'YMCA';
    btn.title = 'Your Mission Chief Alpha';
    btn.addEventListener('click', () => openWindow());
    document.body.append(btn);
    logger.warn('shell', 'navbar not found, using the floating button');
}

function mount() {
    if (mountNav()) {
        document.getElementById('ymca-fab')?.remove();
    } else {
        mountFab();
    }
}

if (typeof GM_registerMenuCommand === 'function') {
    GM_registerMenuCommand('Open YMCA', () => openWindow());
    /* The menu is the launcher by another route, so it answers to the same
     * switches. An element tile has no panel worth opening from here. */
    for (const mod of YMCA.modules) {
        if (mod.mainTile === false || !YMCA.isOn(mod)) continue;
        GM_registerMenuCommand(mod.title, () => openWindow(mod.id));
    }
}
mount();
document.addEventListener('DOMContentLoaded', mount);
setInterval(mount, 5000);

try {
    const w = (typeof unsafeWindow !== 'undefined' ? unsafeWindow : window);
    w.YMCA = YMCA;
    w.ymca = openWindow;
} catch (e) {
    window.YMCA = YMCA;
}
logger.info('shell', 'YMCA ' + YMCA.version + ' loaded', location.href);
`;

function build() {
    const prices = JSON.stringify(JSON.parse(read('data/prices.json')));
    /* The fleet the repo knows about, so a fresh install is not blind until it
     * has watched a few missions. What the player's own game teaches is merged
     * over the top of this, never under it. */
    /* Every capability the game has a word for, read off its own dispatch-order
     * form. Nothing is matched against it that is not matched already: it is
     * what tells "no vehicle in range can do this" apart from "YMCA has never
     * heard of this", which read the same until now. */
    const vehicleFlags = JSON.stringify(
        Object.keys(JSON.parse(read('data/vehicle-flags.json')).flags).sort());
    const vehicleTypes = JSON.stringify(Object.fromEntries(
        Object.entries(JSON.parse(read('data/vehicle-types.json')).types).map(([id, t]) => {
            /* Only what a module asks of a type. The category and the extension it
             * needs are worth keeping in the repo and worth nothing in the page. */
            const lean = { name: t.name };
            if (t.capabilities) lean.capabilities = t.capabilities;
            // How many the vehicle seats and what training they need: both are
            // what a crew requirement is answered with.
            if (t.crew) lean.crew = t.crew;
            if (t.education) lean.education = t.education;
            /* What a vehicle of this type actually carries and actually seats,
             * both MEASURED off the game — the tank off a selection checkbox,
             * the seats off the at-mission table's Crew column. They are not
             * `crew` above, which is the buy page's Max. Crew and a cap
             * somebody set. Without them here every install starts blind on
             * water and on people, however many reports have come back. */
            if (t.tank) lean.tank = t.tank;
            if (t.crewSeen) lean.crewSeen = t.crewSeen;
            /* DERIVED, and kept apart from what was measured. The editor labels
             * each capability checkbox with the vehicle name, so a flag whose
             * label is a type's name names that type. It is added to what a
             * checkbox stated, never substituted for it. */
            if (t.namedBy) lean.namedBy = t.namedBy;
            return [id, lean];
        })));
    const parts = [
        HEADER,
        "(function () {\n'use strict';\n",
        '// ---------- src/planner.js ----------',
        stripExports(read('src/planner.js')),
        '// ---------- src/import-game.js ----------',
        stripExports(stripImports(read('src/import-game.js'))),
        '// ---------- tools/build_from_game.mjs (mapping and dataset build) ----------',
        stripExports(stripImports(
            cutAtMarker(read('tools/build_from_game.mjs'), '// --- CLI ONLY BELOW'))),
        '// ---------- userscripts/src/pf-core.js ----------',
        read('userscripts/src/pf-core.js').replace('__PRICES__', prices),
        '// ---------- userscripts/src/shell.js ----------',
        read('userscripts/src/shell.js').replace('__VERSION__', VERSION),
        '// ---------- modules ----------',
        read('userscripts/src/mod-stepops.js'),
        read('userscripts/src/mod-renamer.js').replace('__VEHICLE_TYPES__', vehicleTypes),
        read('userscripts/src/mod-missionmagician.js')
            .replace('__VEHICLE_TYPES__', vehicleTypes)
            .replace('__VEHICLE_FLAGS__', vehicleFlags),
        read('userscripts/src/mod-recruitroom.js'),
        read('userscripts/src/mod-simpleaao.js'),
        read('userscripts/src/mod-heatmap.js'),
        read('userscripts/src/mod-trackops.js'),
        /* ElementFriend is the switchboard and HighFive is its first
         * element-only tile, so both come after everything they switch: the
         * page lists YMCA.modules, and register order is the order it reads. */
        read('userscripts/src/mod-elementfriend.js'),
        read('userscripts/src/mod-highfive.js'),
        /* EagleEye is a group and ShutEye is in it, so the group registers
         * first: ElementFriend lists in register order. */
        /* EasyEdit is a group too, and its members follow it for the same
         * reason: ElementFriend lists in register order. */
        read('userscripts/src/mod-easyedit.js'),
        read('userscripts/src/mod-switchdispatch.js'),
        read('userscripts/src/mod-eagleeye.js'),
        read('userscripts/src/mod-shuteye.js'),
        read('userscripts/src/mod-stationfascination.js'),
        read('userscripts/src/mod-diagnostics.js')
            .replace('__VEHICLE_TYPES__', vehicleTypes)
            .replace('__VEHICLE_FLAGS__', vehicleFlags),
        BOOT,
        '})();\n',
    ];
    return parts.join('\n');
}

const out = build();
writeFileSync(new URL('userscripts/ymca.user.js', ROOT), out);
console.log(`wrote userscripts/ymca.user.js — YMCA ${VERSION}, ${Math.round(out.length / 1024)} KB`);
