/**
 * Bundle YMCA into one installable userscript.
 *
 * The point of the build is that the algorithm is NOT duplicated: src/planner.js,
 * src/import-game.js and the prerequisite mapping from tools/build_from_game.mjs
 * are the same sources the tests run against, inlined here. Change them once and
 * both the static app and the userscript follow.
 *
 *   node tools/build_ymca.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const ROOT = new URL('..', import.meta.url);
const read = (p) => readFileSync(new URL(p, ROOT), 'utf8');

/** Version lives here, and nowhere else. Steps of 0.0.1, starting at 0.0.0. */
export const VERSION = '0.0.0';

const stripExports = (src) => src.replace(/^export\s+/gm, '');
const cutAtMarker = (src, marker) => {
    const i = src.indexOf(marker);
    return i === -1 ? src : src.slice(0, i);
};
const stripImports = (src) =>
    src.replace(/^import\s+[^;]*;\s*$/gm, '');

const HEADER = `// ==UserScript==
// @name         YMCA — Your Mission Chief Alpha
// @namespace    https://github.com/Kev7ke/pathfinder
// @version      ${VERSION}
// @description  A tool set for MissionChief: build planning, bulk renaming, and a way to hand game data back for support.
// @author       Kev7ke (built with Claude Code)
// @homepageURL  https://github.com/Kev7ke/pathfinder
// @downloadURL  https://raw.githubusercontent.com/Kev7ke/pathfinder/claude/keen-hawking-g3z0ph/userscripts/ymca.user.js
// @updateURL    https://raw.githubusercontent.com/Kev7ke/pathfinder/claude/keen-hawking-g3z0ph/userscripts/ymca.user.js
// @match        *://*.missionchief.com/*
// @match        *://missionchief.com/*
// @match        *://*.missionchief.co.uk/*
// @match        *://missionchief.co.uk/*
// @match        *://*.missionchief-australia.com/*
// @match        *://*.missionchief-japan.com/*
// @match        *://*.missionchief-korea.com/*
// @run-at       document-idle
// @grant        GM_registerMenuCommand
// @grant        GM_xmlhttpRequest
// @grant        GM_info
// @connect      api.lss-manager.de
// ==/UserScript==

/*
 * Generated by tools/build_ymca.mjs — do not edit this file.
 * Sources: userscripts/src/*.js, src/planner.js, src/import-game.js,
 * tools/build_from_game.mjs, data/prices.json
 */
`;

const BOOT = `
// ---------- boot ----------
YMCA.logger = logger;

function mountLauncher() {
    if (document.getElementById('ymca-fab') || !document.body) return;
    const btn = document.createElement('button');
    btn.id = 'ymca-fab';
    btn.type = 'button';
    btn.textContent = 'YMCA';
    btn.title = 'Your Mission Chief Alpha';
    btn.addEventListener('click', () => openWindow());
    document.body.append(btn);
}

if (typeof GM_registerMenuCommand === 'function') {
    for (const mod of YMCA.modules) {
        GM_registerMenuCommand(mod.title, () => openWindow(mod.id));
    }
}
mountLauncher();
document.addEventListener('DOMContentLoaded', mountLauncher);
setInterval(mountLauncher, 5000);

try {
    const w = (typeof unsafeWindow !== 'undefined' ? unsafeWindow : window);
    w.YMCA = YMCA;
    w.ymca = openWindow;
} catch (e) {
    window.YMCA = YMCA;
}
logger.info('shell', 'YMCA ' + YMCA.version + ' loaded', location.href);
`;

function build() {
    const prices = JSON.stringify(JSON.parse(read('data/prices.json')));
    const parts = [
        HEADER,
        "(function () {\n'use strict';\n",
        '// ---------- src/planner.js ----------',
        stripExports(read('src/planner.js')),
        '// ---------- src/import-game.js ----------',
        stripExports(stripImports(read('src/import-game.js'))),
        '// ---------- tools/build_from_game.mjs (mapping and dataset build) ----------',
        stripExports(stripImports(
            cutAtMarker(read('tools/build_from_game.mjs'), '// --- CLI ONLY BELOW'))),
        '// ---------- userscripts/src/pf-core.js ----------',
        read('userscripts/src/pf-core.js').replace('__PRICES__', prices),
        '// ---------- userscripts/src/shell.js ----------',
        read('userscripts/src/shell.js').replace('__VERSION__', VERSION),
        '// ---------- modules ----------',
        read('userscripts/src/mod-pathfinder.js'),
        read('userscripts/src/mod-renamer.js'),
        read('userscripts/src/mod-diagnostics.js'),
        BOOT,
        '})();\n',
    ];
    return parts.join('\n');
}

const out = build();
writeFileSync(new URL('userscripts/ymca.user.js', ROOT), out);
console.log(`wrote userscripts/ymca.user.js — YMCA ${VERSION}, ${Math.round(out.length / 1024)} KB`);
